### ISSUE TITLE
Portal storage is full

### ISSUE THREAD

**Issue by Simon-van-Diepen** [TUDelftGeodesy/caroline#294]
```
sending incremental file list
nl_aldeboarn_dsc_110_20250605_uploaded20250611T020007.csv
nl_aldeboarn_dsc_110_20250605_uploaded20250611T020007.json
rsync: write failed on "/tmp/nl_aldeboarn_dsc_110_20250605_uploaded20250611T020007.csv": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.1]
chmod: cannot access '/tmp/nl_aldeboarn_dsc_110_20250605_uploaded20250611T020007.json': No such file or directory
chmod: cannot access '/tmp/nl_aldeboarn_dsc_110_20250605_uploaded20250611T020007.csv': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/pman", line 9, in <module>
    load_entry_point('portalmanager==1.0-acc', 'console_scripts', 'pman')()
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/__main__.py", line 126, in main
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/helper_functions.py", line 402, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/pman.py", line 810, in add_viewer_data_layer
    layer = add_data(data_file, layer, c, v, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/helper_functions.py", line 402, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/pman.py", line 126, in add_data
    raise IOError("File not found: %s" % infile)
IOError: File not found: /tmp/nl_aldeboarn_dsc_110_20250605_uploaded20250611T020007.csv
```

**Comment by Simon-van-Diepen** [comment]
@FreekvanLeijen @tud-nhjansen I am reopening this one since there are still errors appearing:

```
find: ‘/tmp/systemd-private-fc11e3896b3c4a718bc285529d43c0cb-systemd-timesyncd.service-6fFMer’: Permission denied
find: ‘/tmp/systemd-private-fc11e3896b3c4a718bc285529d43c0cb-systemd-timesyncd.service-6fFMer’: Permission denied
sending incremental file list
nl_limburg_asc_088_20250709_uploaded20250714T120433.csv
nl_limburg_asc_088_20250709_uploaded20250714T120433.json

sent 17,535,898 bytes  received 54 bytes  5,010,272.00 bytes/sec
total size is 17,531,387  speedup is 1.00
['nl_limburg_asc_088_20250709_uploaded20250714t120433', (None, None)]
find: ‘/tmp/systemd-private-fc11e3896b3c4a718bc285529d43c0cb-systemd-timesyncd.service-6fFMer’: Permission denied
find: ‘/tmp/systemd-private-fc11e3896b3c4a718bc285529d43c0cb-systemd-timesyncd.service-6fFMer’: Permission denied
```

**Comment by Simon-van-Diepen** [comment]
And another one from `nl_groningen`, the biggest other one

```
sending incremental file list
nl_groningen_cubic_asc_015_20250704_uploaded20250714T140021.csv
nl_groningen_cubic_asc_015_20250704_uploaded20250714T140021.json

sent 2,012,724,042 bytes  received 54 bytes  82,152,003.92 bytes/sec
total size is 2,012,232,536  speedup is 1.00
ERROR 1: INSERT command for new feature failed.
ERROR:  could not extend file "base/92900/75597571.1": No space left on device
HINT:  Check free disk space.

Command: INSERT INTO "nl_groningen"."nl_groningen_cubic_asc_015_20250704_uploaded20250714t140021" ("geom900913" , "pnt_id", "pnt_lat", "pnt_lon", "pnt_demheight", "pnt_height", "pnt_azimuth", "pnt_range", "pnt_quality", "pnt_linear", "d_20180223", "d_20180301", "d_20180307", "d_20180313", "d_20180319", "d_20180325", "d_20180331", "d_20180406", "d_20180412", "d_20180424", "d_20180430", "d_20180506", "d_20180512", "d_20180518", "d_20180524", "d_20180530", "d_20180605", "d_20180611", "d_20180617", "d_20180623", "d_20180705", "d_20180711", "d_20180717", "d_20180723", "d_20180729", "d_20180804", "d_20180810", "d_20180816", "d_20180822", "d_20180828", "d_20180903", "d_20180909", "d_20180915", "d_20180921", "d_20180927", "d_20181003", "d_20181009", "d_20181015", "d_20181021", "d_20181027", "d_20181102", "d_20181108", "d_20181114", "d_20181120", "d_20181126", "d_20181202", "d_20181208", "d_20181214", "d_20181220", "d_20181226", "d_20190101", "d_20190107", "d_20190113", "d_20190119", "d_20190125", "d_20190131", "d_20190206", "d_20190218", "d_20190224", "d_20190302", "d_20190308", "d_20190314", "d_20190320", "d_20190326", "d_20190401", "d_20190407", "d_20190413", "d_20190419", "d_20190501", "d_20190507", "d_20190513", "d_20190519", "d_20190525", "d_20190531", "d_20190606", "d_20190612", "d_20190618", "d_20190630", "d_20190706", "d_20190712", "d_20190718", "d_20190724", "d_20190730", "d_20190805", "d_20190811", "d_20190817", "d_20190829", "d_20190904", "d_20190910", "d_20190916", "d_20190922", "d_20190928", "d_20191004", "d_20191010", "d_20191016", "d_20191028", "d_20191103", "d_20191109", "d_20191115", "d_20191121", "d_20191127", "d_20191203", "d_20191209", "d_20191215", "d_20191227", "d_20200102", "d_20200108", "d_20200114", "d_20200120", "d_20200126", "d_20200201", "d_20200207", "d_20200213", "d_20200225", "d_20200302", "d_20200308", "d_20200314", "d_20200320", "d_20200326", "d_20200401", "d_20200407", "d_20200413", "d_20200425", "d_20200501", "d_20200507", "d_20200513", "d_20200519", "d_20200525", "d_20200531", "d_20200606", "d_20200612", "d_20200624", "d_20200630", "d_20200706", "d_20200712", "d_20200718", "d_20200724", "d_20200730", "d_20200805", "d_20200811", "d_20200817", "d_20200823", "d_20200829", "d_20200904", "d_20200910", "d_20200916", "d_20200922", "d_20200928", "d_20201004", "d_20201010", "d_20201022", "d_20201028", "d_20201103", "d_20201109", "d_20201115", "d_20201121", "d_20201127", "d_20201203", "d_20201209", "d_20201215", "d_20201221", "d_20201227", "d_20210102", "d_20210108", "d_20210114", "d_20210120", "d_20210126", "d_20210201", "d_20210207", "d_20210219", "d_20210225", "d_20210303", "d_20210309", "d_20210315", "d_20210321", "d_20210327", "d_20210402", "d_20210408", "d_20210414", "d_20210420", "d_20210426", "d_20210502", "d_20210508", "d_20210514", "d_20210520", "d_20210526", "d_20210601", "d_20210607", "d_20210613", "d_20210619", "d_20210625", "d_20210701", "d_20210707", "d_20210713", "d_20210719", "d_20210725", "d_20210731", "d_20210806", "d_20210812", "d_20210818", "d_20210824", "d_20210830", "d_20210905", "d_20210911", "d_20210917", "d_20210923", "d_20210929", "d_20211005", "d_20211011", "d_20211017", "d_20211023", "d_20211029", "d_20211104", "d_20211110", "d_20211116", "d_20211122", "d_20211128", "d_20211204", "d_20211210", "d_20211216", "d_20211222", "d_20211228", "d_20220109", "d_20220121", "d_20220202", "d_20220214", "d_20220226", "d_20220310", "d_20220322", "d_20220403", "d_20220415", "d_20220427", "d_20220509", "d_20220521", "d_20220602", "d_20220614", "d_20220626", "d_20220708", "d_20220720", "d_20220801", "d_20220813", "d_20220825", "d_20220906", "d_20220918", "d_20220930", "d_20221012", "d_20221024", "d_20221105", "d_20221117", "d_20221129", "d_20221211", "d_20221223", "d_20230104", "d_20230116", "d_20230128", "d_20230209", "d_20230221", "d_20230305", "d_20230317", "d_20230329", "d_20230410", "d_20230422", "d_20230504", "d_20230516", "d_20230528", "d_20230609", "d_20230621", "d_20230703", "d_20230715", "d_20230727", "d_20230808", "d_20230820", "d_20230901", "d_20230913", "d_20230925", "d_20231007", "d_20231019", "d_20231112", "d_20231124", "d_20231206", "d_20231218", "d_20231230", "d_20240111", "d_20240123", "d_20240204", "d_20240216", "d_20240228", "d_20240311", "d_20240323", "d_20240404", "d_20240416", "d_20240428", "d_20240510", "d_20240522", "d_20240603", "d_20240615", "d_20240627", "d_20240709", "d_20240721", "d_20240802", "d_20240814", "d_20240826", "d_20240907", "d_20240919", "d_20241001", "d_20241013", "d_20241025", "d_20241106", "d_20241118", "d_20241130", "d_20241212", "d_20241224", "d_20250105", "d_20250117", "d_20250129", "d_20250210", "d_20250222", "d_20250306", "d_20250318", "d_20250330", "d_20250411", "d_20250423", "d_20250505", "d_20250511", "d_20250517", "d_20250523", "d_20250529", "d_20250604", "d_20250610", "d_20250616", "d_20250622", "d_20250704", "a_20180223", "a_20180301", "a_20180307", "a_20180313", "a_20180319", "a_20180325", "a_20180331", "a_20180406", "a_20180412", "a_20180424", "a_20180430", "a_20180506", "a_20180512", "a_20180518", "a_20180524", "a_20180530", "a_20180605", "a_20180611", "a_20180617", "a_20180623", "a_20180705", "a_20180711", "a_20180717", "a_20180723", "a_20180729", "a_20180804", "a_20180810", "a_20180816", "a_20180822", "a_20180828", "a_20180903", "a_20180909", "a_20180915", "a_20180921", "a_20180927", "a_20181003", "a_20181009", "a_20181015", "a_20181021", "a_20181027", "a_20181102", "a_20181108", "a_20181114", "a_20181120", "a_20181126", "a_20181202", "a_20181208", "a_20181214", "a_20181220", "a_20181226", "a_20190101", "a_20190107", "a_20190113", "a_20190119", "a_20190125", "a_20190131", "a_20190206", "a_20190218", "a_20190224", "a_20190302", "a_20190308", "a_20190314", "a_20190320", "a_20190326", "a_20190401", "a_20190407", "a_20190413", "a_20190419", "a_20190501", "a_20190507", "a_20190513", "a_20190519", "a_20190525", "a_20190531", "a_20190606", "a_20190612", "a_20190618", "a_20190630", "a_20190706", "a_20190712", "a_20190718", "a_20190724", "a_20190730", "a_20190805", "a_20190811", "a_20190817", "a_20190829", "a_20190904", "a_20190910", "a_20190916", "a_20190922", "a_20190928", "a_20191004", "a_20191010", "a_20191016", "a_20191028", "a_20191103", "a_20191109", "a_20191115", "a_20191121", "a_20191127", "a_20191203", "a_20191209", "a_20191215", "a_20191227", "a_20200102", "a_20200108", "a_20200114", "a_20200120", "a_20200126", "a_20200201", "a_20200207", "a_20200213", "a_20200225", "a_20200302", "a_20200308", "a_20200314", "a_20200320", "a_20200326", "a_20200401", "a_20200407", "a_20200413", "a_20200425", "a_20200501", "a_20200507", "a_20200513", "a_20200519", "a_20200525", "a_20200531", "a_20200606", "a_20200612", "a_20200624", "a_20200630", "a_20200706", "a_20200712", "a_20200718", "a_20200724", "a_20200730", "a_20200805", "a_20200811", "a_20200817", "a_20200823", "a_20200829", "a_20200904", "a_20200910", "a_20200916", "a_20200922", "a_20200928", "a_20201004", "a_20201010", "a_20201022", "a_20201028", "a_20201103", "a_20201109", "a_20201115", "a_20201121", "a_20201127", "a_20201203", "a_20201209", "a_20201215", "a_20201221", "a_20201227", "a_20210102", "a_20210108", "a_20210114", "a_20210120", "a_20210126", "a_20210201", "a_20210207", "a_20210219", "a_20210225", "a_20210303", "a_20210309", "a_20210315", "a_20210321", "a_20210327", "a_20210402", "a_20210408", "a_20210414", "a_20210420", "a_20210426", "a_20210502", "a_20210508", "a_20210514", "a_20210520", "a_20210526", "a_20210601", "a_20210607", "a_20210613", "a_20210619", "a_20210625", "a_20210701", "a_20210707", "a_20210713", "a_20210719", "a_20210725", "a_20210731", "a_20210806", "a_20210812", "a_20210818", "a_20210824", "a_20210830", "a_20210905", "a_20210911", "a_20210917", "a_20210923", "a_20210929", "a_20211005", "a_20211011", "a_20211017", "a_20211023", "a_20211029", "a_20211104", "a_20211110", "a_20211116", "a_20211122", "a_20211128", "a_20211204", "a_20211210", "a_20211216", "a_20211222", "a_20211228", "a_20220109", "a_20220121", "a_20220202", "a_20220214", "a_20220226", "a_20220310", "a_20220322", "a_20220403", "a_20220415", "a_20220427", "a_20220509", "a_20220521", "a_20220602", "a_20220614", "a_20220626", "a_20220708", "a_20220720", "a_20220801", "a_20220813", "a_20220825", "a_20220906", "a_20220918", "a_20220930", "a_20221012", "a_20221024", "a_20221105", "a_20221117", "a_20221129", "a_20221211", "a_20221223", "a_20230104", "a_20230116", "a_20230128", "a_20230209", "a_20230221", "a_20230305", "a_20230317", "a_20230329", "a_20230410", "a_20230422", "a_20230504", "a_20230516", "a_20230528", "a_20230609", "a_20230621", "a_20230703", "a_20230715", "a_20230727", "a_20230808", "a_20230820", "a_20230901", "a_20230913", "a_20230925", "a_20231007", "a_20231019", "a_20231112", "a_20231124", "a_20231206", "a_20231218", "a_20231230", "a_20240111", "a_20240123", "a_20240204", "a_20240216", "a_20240228", "a_20240311", "a_20240323", "a_20240404", "a_20240416", "a_20240428", "a_20240510", "a_20240522", "a_20240603", "a_20240615", "a_20240627", "a_20240709", "a_20240721", "a_20240802", "a_20240814", "a_20240826", "a_20240907", "a_20240919", "a_20241001", "a_20241013", "a_20241025", "a_20241106", "a_20241118", "a_20241130", "a_20241212", "a_20241224", "a_20250105", "a_20250117", "a_20250129", "a_20250210", "a_20250222", "a_20250306", "a_20250318", "a_20250330", "a_20250411", "a_20250423", "a_20250505", "a_20250511", "a_20250517", "a_20250523", "a_20250529", "a_20250604", "a_20250610", "a_20250616", "a_20250622", "a_20250704") VALUES ('0101000020110F0000AF245A43AA502841FA48875112E25A41'::GEOMETRY, 'S1asc015az00002840r00015828', 53.34591689, 7.15739109, 57.24, 57.24, 2840, 15828, 0.79, 0.0005, 0, 0.0067, 0.0072, 0.0081, 0.0005, 0.0084, -0.0018, 0.0071, 0.0032, 0.0053, 0.0134, -0.0007, 0.0139, 0.0114, 0.0056, 0.0084, 0.0094, 0.0076, 0.0135, 0.0077, 0.0076, 0.0136, 0.002, 0.0092, 0.0061, 0.0124, 0.0106, 0.0103, -0.0019, 0.0123, 0.0048, 0.01, 0.0062, 0.0109, 0.0155, 0.0073, -0.0006, 0.0081, 0.004, 0.0088, 0.0027, 0.0148, 0.0052, 0.0098, 0.0067, 0.0077, 0.0071, 0.0086, -0.0024, 0.0074, 0.0012, 0.0102, 0.0015, 0.0114, 0.0121, 0.0116, 0.0043, 0.0079, 0.0074, 0.0086, 0.0123, 0.0105, 0.0174, 0.0075, 0.0112, 0.004, 0.0137, 0.0102, 0.0108, 0.014, 0.0087, 0.014, 0.0081, 0.0109, 0.0082, 0.0146, 0.0012, 0.011, 0.0055, 0.0122, 0.017, 0.011, 0.014, 0.0123, 0.0125, 0.0085, 0.0086, 0.0244, 0.0074, 0.0082, 0.0055, 0.0144, 0.0051, 0.0089, 0.0045, 0.0014, 0.0072, 0.0076, 0.0099, 0.0097, 0.0096, 0.0088, 0.0068, 0.0093, -0.0001, 0.0073, 0.0045, 0.0104, 0.0072, 0.0106, 0.0068, 0.0064, 0.0026, 0.0114, 0.013, 0.0074, 0.0086, 0.0063, 0.0102, 0.0086, 0.0143, 0.0081, 0.0046, 0.0144, 0.0083, 0.0119, 0.0114, 0.0162, 0.0108, 0.0166, 0.0147, 0.0134, 0.0174, 0.0115, 0.0127, 0.014, 0.0178, 0.0127, 0.0138, 0.0124, 0.0162, 0.0095, 0.0146, 0.0077, 0.0145, 0.01, 0.0115, 0.0143, 0.0133, 0.0081, 0.012, 0.0088, 0.0135, 0.0126, 0.013, 0.0095, 0.0037, 0.012, 0.0039, 0.0091, 0.0082, 0.0152, 0.0085, 0.0081, 0.0064, 0.0101, 0.0068, 0.0087, 0.0104, 0.004, 0.0078, 0.006, 0.0112, 0.0087, 0.0116, 0.0089, 0.0123, 0.0085, 0.0106, 0.0049, 0.0121, 0.0125, 0.0146, 0.0117, 0.0149, 0.0165, 0.0109, 0.013, 0.0157, 0.0098, 0.0158, 0.0111, 0.0123, 0.0149, 0.013, 0.018, 0.0147, 0.0164, 0.021, 0.0139, 0.0115, 0.009, 0.013, 0.0132, 0.012, 0.01, 0.0103, 0.0187, 0.0104, 0.0089, 0.0096, 0.0073, 0.0061, 0.0069, 0.011, 0.01, 0.0113, 0.0104, 0.0065, 0.0125, 0.0105, 0.0089, 0.0093, 0.0028, 0.0092, 0.0072, 0.0117, 0.009, 0.0078, 0.0072, 0.0113, 0.0093, 0.0079, 0.0095, 0.0091, 0.0068, 0.0132, 0.0166, 0.0132, 0.0167, 0.0126, 0.009, 0.0078, 0.0122, 0.0126, 0.0079, 0.0105, 0.0095, 0.0117, 0.0109, 0.0128, 0.0137, 0.0131, 0.0077, 0.0101, 0.0019, 0.0021, 0.011, 0.0038, 0.0059, 0.0128, 0.024, 0.0151, 0.0146, 0.0148, 0.0126, 0.0109, 0.0038, 0.0191, 0.0161, 0.0136, 0.0056, 0.0143, 0.0159, 0.0154, 0.0166, 0.011, 0.0113, 0.0124, 0.0068, 0.012, 0.0092, 0.0058, 0.0107, 0.0086, 0.0047, 0.0068, 0.0086, 0.0054, 0.0078, 0.007, 0.015, 0.0152, 0.0116, 0.0096, 0.0178, 0.019, 0.0105, 0.0137, -0.0066, -0.0042, 0.0091, 0.0091, 0.0142, 0.011, 0.0085, 0.007, 0.0086, 0.0149, 0.0109, 0.0098, 0.0115, 0.0092, 0.0115, 0.0086, 0.0109, 0.0112, 0.0107, 0.0111, 0.0094, 0.0081, 0.0134, 0.0134, 0.0145, 0.0187, 0.0139, 0.0214, 0.0135, 0.0201, 0.0199, 0.0138, 0.0119, 62.24, 127.99, 108.29, 94.72, 107.63, 138.33, 53.54, 110.34, 69.85, 103.67, 137.74, 119.78, 98.26, 108.12, 164.89, 86.12, 104.93, 96.29, 123.3, 39.79, 81.23, 81.92, 43.19, 74.88, 19.79, 120.3, 55.34, 167.79, 138.5, 118.61, 61.92, 119.36, 85.35, 131.72, 38.06, 85.94, 26.8, 112.53, 84.83, 58.03, 50.56, 82.1, 68.45, 126.39, 73.78, 80.84, 49.78, 95.89, 62.87, 97.65, 90.79, 39.43, 63.95, 87.63, 102.87, 122.92, 31.36, 13.82, 99.17, 110.74, 79.13, 104.78, 84.93, 86.46, 128.15, 59.37, 136.36, 94.28, 133.1, 57.6, 95.89, 108.79, 76.8, 119.73, 94.48, 174.17, 105.47, 110.19, 190.3, 93.38, 122.99, 130.98, 104.14, 129.46, 155.12, 127.9, 98.11, 76.67, 92.2, 130.37, 100.86, 93.98, 129.04, 57.63, 97.65, 34.58, 87.15, 132.79, 97.7, 116.29, 90.05, 89.68, 79.49, 76.44, 45.68, 104.51, 78.42, 104.45, 106.02, 111.79, 84.99, 127.2, 31.2, 106.17, 77.53, 125.74, 50.03, 67.13, 78.22, 125.06, 118.58, 45.92, 132.43, 40.86, 123.33, 73.3, 150.43, 106.09, 102.33, 114.91, 119.33, 151.03, 99, 94.86, 91.68, 112.99, 81.77, 98.95, 69.11, 147.7, 83.69, 137.08, 78.96, 113.75, 84.09, 154.14, 118.08, 117.83, 90.88, 102.77, 69.12, 54.32, 101.44, 86.15, 71.37, 154.76, 67.44, 82.72, 82.93, 36.14, 72.62, 103.28, 86.08, 71.13, 103.64, 79.77, 102.52, 158.17, 98.91, 64.77, 64.6, 109.64, 83.98, 97.55, 106.91, 132.84, 73.51, 128.52, 79.11, 80.5, 77.44, 69.62, 101.6, 150.43, 60.7, 106.69, 136.8, 88.09, 112.3, 85.9, 96.1, 108.92, 87.99, 137.96, 82.56, 73.51, 69.34, 99.94, 109.11, 140.87, 123.97, 118.52, 48.49, 101.21, 48.15, 93.44, 8.18, 125.91, 121.16, 118.71, 136.95, 61.89, 104.64, 100.08, 90.97, 127.82, 58.67, 136.95, 35.83, 73.32, 56.33, 104.83, 76.82, 54.81, 73.82, 64.7, 105.71, 150.12, 86.06, 199.79, 75.45, 114.59, 138.53, 92.38, 40.83, 88.4, 118.75, 62.7, 100.32, 81.42, 85.34, 76.47, 42.14, 57.93, 66.01, 70.23, 90.65, 101.47, 133.2, 125.47, 80.72, 62.93, 90.31, 118.45, 50.76, 10.96, 163.36, 43.66, 92.99, 111.91, 94.33, 111.59, 125.59, 44.65, 85.31, 94.81, 73.95, 74.19, 113.75, 102.05, 46.94, 121.72, 128.45, 84.41, 74.97, 28.41, 74.3, 107.35, 16.04, 67.86, 135.28, 49.28, 66.06, 73.2, 91.14, 114.11, 118.99, 106.64, 61.56, 125.29, 110.95, 92.61, 56.22, 110.65, 156.84, 73.93, 37.42, 80.33, 33.32, 28.7, 85.03, 75.38, 52.7, 45.07, 110.14, 86.5, 103.68, 52.73, 56.55, 75.95, 27.52, 89.7, 51.55, 83.61, 60.61, 70.41, 135.1, 100.12, 92.81, 54.12, 32.85, 51.83, 53.46, 118.06, 104.98, 32.17, 90.82, 118.9, 113.85, 87.08, 73.5, 33.62) RETURNING "ogc_fid"
ERROR 1: Terminating translation prematurely after failed
translation of layer nl_groningen_cubic_asc_015_20250704_uploaded20250714t140021 (use -skipfailures to skip errors)

Traceback (most recent call last):
  File "/usr/local/bin/pman", line 9, in <module>
    load_entry_point('portalmanager==1.0-acc', 'console_scripts', 'pman')()
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/__main__.py", line 126, in main
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/helper_functions.py", line 402, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/pman.py", line 810, in add_viewer_data_layer
    layer = add_data(data_file, layer, c, v, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/helper_functions.py", line 402, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/pman.py", line 192, in add_data
    helper.psycopg_commit(sql, c.name)
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/helper_functions.py", line 470, in psycopg_commit
    cur.execute(sql)
psycopg2.OperationalError: could not extend file "base/92900/1249": No space left on device
HINT:  Check free disk space.

find: ‘/tmp/systemd-private-fc11e3896b3c4a718bc285529d43c0cb-systemd-timesyncd.service-6fFMer’: Permission denied
find: ‘/tmp/systemd-private-fc11e3896b3c4a718bc285529d43c0cb-systemd-timesyncd.service-6fFMer’: Permission denied
```

**Comment by FreekvanLeijen** [comment]
@Simon-van-Diepen @tud-nhjansen With the help of Jeroen at SG, I should have resolved the problem. So uploading to the portal should work again.

The issue is that the root partition is relatively small (although 1TB in size). The issue was that we were having 3 copies on the data in the same partition:

/tmp > where we upload the data. Was resolved earlier.
/etc > where the postgresql database is hosted.
/var > where the web portal resides, which also contained a copy of the .csv for download of the data in the portal.

Both /etc and /var where about 450 GB large, mainly because of the datasets. The .csv files to download are not really needed, so for now, Jeroen made a copy of these files to the /home directory (other partition).

So currently we have 430 GB of space again. This should give us a couple of months to come to a long-term solution, e.g.:

1) at least remove/archive these .csv files. But at a certain stage, the postgresql database will be 1TB large
2) limit/clean up the number of layers in the portal
3) come to our own TUD portal implementation + server
4) setup a new server + portal environment at SG.

To be discussed.

**Comment by Simon-van-Diepen** [comment]
@FreekvanLeijen a while ago our server was reset / upgraded when layers did not show up any more. Did that affect storage space on the SkyGeo servers? Or are these issues still lingering?

**Comment by Simon-van-Diepen** [comment]
Since 18 December the storage was completely full. On 9 January about 100GB of data from one of the viewers (`id_jakarta`) was removed. On 10 January `nl_groningen` still encountered an issue:

```
sending incremental file list
nl_groningen_cubic_los_dsc_037_20260108_uploaded20260111T090102.csv
nl_groningen_cubic_los_dsc_037_20260108_uploaded20260111T090102.json

sent 2,072,643,276 bytes  received 54 bytes  78,212,955.85 bytes/sec
total size is 2,072,137,146  speedup is 1.00
ERROR 1: 'CREATE INDEX "nl_groningen_cubic_los_dsc_037_20260108_uploaded20260111t090102_geom_idx" ON "nl_groningen"."nl_groningen_cubic_los_dsc_037_20260108_uploaded20260111t090102" USING GIST ("geom900913")' failed for layer nl_groningen.nl_groningen_cubic_los_dsc_037_20260108_uploaded20260111t090102, index creation has failed.
ERROR 1: Terminating translation prematurely after failed
translation of layer nl_groningen_cubic_los_dsc_037_20260108_uploaded20260111t090102 (use -skipfailures to skip errors)

Traceback (most recent call last):
  File "/usr/local/bin/pman", line 9, in <module>
    load_entry_point('portalmanager==1.0-acc', 'console_scripts', 'pman')()
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/__main__.py", line 126, in main
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/helper_functions.py", line 402, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/pman.py", line 810, in add_viewer_data_layer
    layer = add_data(data_file, layer, c, v, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/helper_functions.py", line 402, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/pman.py", line 192, in add_data
    helper.psycopg_commit(sql, c.name)
  File "/usr/local/lib/python2.7/dist-packages/portalmanager-1.0_acc-py2.7.egg/portalmanager/helper_functions.py", line 470, in psycopg_commit
    cur.execute(sql)
psycopg2.ProgrammingError: relation "nl_groningen.nl_groningen_cubic_los_dsc_037_20260108_uploaded20260111t090102" does not exist

find:    ^`^x/tmp/systemd-private-cb5d9d16e3f04a8ab52eb37ed77c4140-systemd-timesyncd.service-n6C3od   ^`^y: Permission denied
find:    ^`^x/tmp/systemd-private-cb5d9d16e3f04a8ab52eb37ed77c4140-systemd-timesyncd.service-n6C3od   ^`^y: Permission denied
```

@FreekvanLeijen can you see what happened on the server that caused this?
